const List<String> todoExamples = [
  'Buy groceries',
  'Finish homework',
  'Go for a run',
  'Call mom',
  'Pay bills',
  'Clean the house',
  'Read a book',
  'Schedule doctor\'s appointment',
  'Walk the dog',
  'Write a blog post',
  'Prepare dinner',
  'Organize closet',
  'Start a new project',
  'Attend meeting at work',
  'Do laundry',
  'Visit the dentist',
  'Plan weekend trip',
  'Send thank-you cards',
  'Practice playing guitar',
  'Watch a movie',
  'Update resume',
  'Water the plants',
  'Learn a new language',
  'Volunteer at local shelter',
  'Fix broken chair',
];
